# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: live-video-alert-agent
description: A Helm chart for deploying the Live Video Alert Agent with OpenVINO VLM inference
type: application
version: 2026.1.0-rc1-helm
appVersion: "2.0.0"

dependencies:
  - name: ovms
    version: 1.0.1
    repository: "file://subchart/ovms"
  - name: ovms-llm
    version: 1.0.1
    repository: "file://subchart/ovms-llm"
    condition: ovms-llm.enabled
  - name: app
    version: 1.0.1
    repository: "file://subchart/app"
  - name: metrics-service
    version: 1.0.1
    repository: "file://subchart/metrics-service"
  - name: collector
    version: 1.0.1
    repository: "file://subchart/collector"
